# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 15:54
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('djcms_custom_menu', '0004_djcmscustommenu_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djcmscustommenu',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='djcmscustommenu',
            unique_together=set([('slug', 'site')]),
        ),
    ]
