# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 03:53
from __future__ import unicode_literals

import djcms_custom_menu.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcms_custom_menu', '0006_auto_20190201_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djcmscustommenu',
            name='site',
            field=models.ForeignKey(default=djcms_custom_menu.models.get_current_site, help_text='The site the menu is accessible at.', on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='site'),
        ),
    ]
